name: K3s Release

on:
  push:
    tags:
    - "v*"

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  upload-release-assets:
    name: Prepare and Upload Release Assets
    permissions: 
      contents: write # Needed to update release with assets
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Read Prime artifacts secrets
      uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
      if: ${{ github.repository_owner == 'k3s-io' }}
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader/credentials accessKeyId | AWS_ACCESS_KEY_ID ;
          secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader/credentials secretAccessKey | AWS_SECRET_ACCESS_KEY ;
          secret/data/github/repo/${{ github.repository }}/prime-artifacts-uploader/credentials primeArtifactsBucketName | PRIME_ARTIFACTS_BUCKET_NAME

    - name: Read registry secrets (staging)
      uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
      if: ${{ contains(github.ref_name, '-rc') && github.repository_owner == 'k3s-io' }}
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/k3s-suse-registry-stg/credentials registry | REGISTRY

    - name: Read registry secrets (prime)
      uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
      if: ${{ !contains(github.ref_name, '-rc') && github.repository_owner == 'k3s-io' }}
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/k3s-suse-registry/credentials registry | REGISTRY

    - name: Configure AWS Credentials (s3)
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
      if: ${{ github.repository_owner == 'k3s-io' }}
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update Image Registry for Prime/Staging
      if: ${{ github.repository_owner == 'k3s-io' }}
      env:
        REGISTRY: ${{ env.REGISTRY }}
      run: sed -i "s|docker.io|${REGISTRY}|g" dist/artifacts/k3s-images.txt

    - name: Upload Assets to S3
      env:
        BUCKET: "my-bucket"
      run: |
        S3_PATH="s3://${BUCKET}/k3s/${GITHUB_REF_NAME}"
        aws s3 sync dist/artifacts/ "$S3_PATH" --quiet --no-progress --exclude "*" --include "k3s*" --include "sha256sum*"

